version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: cofound_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: